[package]
name = "runner"
version = "0.1.0"
edition = "2024"

[dependencies]
freedesktop-file-parser = "0.2.0"
global-hotkey = "0.7.0"
iced = { version = "0.13.1", features = ["advanced"] }
unicode-segmentation = "1.12.0"
notify = "8.0.0"
rand = "0.9.1"
serde = "1.0.219"
smol = "2.0.2"
toml = "0.8.23"
